### ISSUE TITLE
Update `README.md`

### ISSUE THREAD

**Issue by sam-mata** [sam-mata/python-template#3]
### Details
Several sections of the project could be updated to be more useful.

## ToDo
- [x] Sections should be enumerated, and split with dividers.
- [x] Placeholder table should be provided for tools section, detailing tool name, type, and usage.
- [x] Overview should list current paths.
- [x] Blurbs should be more detailed.
- [x] Authorship section should be filled with placeholder @sam-mata .
- [x] `.github/labeller.yml` should use placeholder example values.
- [x] Note should be updated to format correctly.
